package internal

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/Dvorinka/docsync/internal/find"
)

// Baseline lets a repo adopt docsync incrementally: current drift is
// recorded once (`check --baseline-out`), then future runs with
// `--baseline` suppress exactly those findings. New drift still fires.

// fingerprint identifies a finding stably across line-number churn:
// category + key (the key already carries the path for path findings).
func fingerprint(f find.Finding) string {
	return f.Category + "|" + f.Key
}

// LoadBaseline reads a baseline file — one fingerprint per line,
// '#' comments allowed.
func LoadBaseline(path string) (map[string]bool, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("cannot read baseline %s: %w", path, err)
	}
	defer f.Close()
	out := map[string]bool{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		l := strings.TrimSpace(sc.Text())
		if l == "" || strings.HasPrefix(l, "#") {
			continue
		}
		out[l] = true
	}
	return out, sc.Err()
}

// WriteBaseline records the current finding set as a baseline file.
func WriteBaseline(path string, findings []find.Finding) error {
	fps := make([]string, 0, len(findings))
	for _, f := range findings {
		fps = append(fps, fingerprint(f))
	}
	sort.Strings(fps)
	var b strings.Builder
	b.WriteString("# docsync baseline — generated by `docsync check --baseline-out`\n")
	b.WriteString("# findings listed here are suppressed by `docsync check --baseline`\n")
	for _, fp := range fps {
		b.WriteString(fp + "\n")
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// ApplyBaseline removes baselined findings and reports how many were
// suppressed.
func ApplyBaseline(res Result, baseline map[string]bool) Result {
	if len(baseline) == 0 {
		return res
	}
	var kept []find.Finding
	suppressed := 0
	for _, f := range res.Findings {
		if baseline[fingerprint(f)] {
			suppressed++
			continue
		}
		kept = append(kept, f)
	}
	res.Findings = kept
	res.Summary = find.Summarize(kept)
	res.Summary.Suppressed = suppressed
	return res
}
